---
title: "World Food Day"
author: "Xuan Beatty, Madison Johnson, Kapahi Kawai Puaa, Andrea Sanchez Hidalgo"
date: "2025-12-15"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  results = 'markup',
  warning = FALSE,
  message = FALSE,
  error = FALSE)

```

## Libraries needed


```{r cars}

## install.packages("tidytuesdayR")

library(dplyr)
library(tidyr)
library(broom)
library(purrr)
library(ggplot2)
library(stringr)
library(tidytuesdayR)
```

## Loading the data

```{r reading in the data}

tuesdata <- tidytuesdayR::tt_load('2025-10-14')
## OR
tuesdata <- tidytuesdayR::tt_load(2025, week = 41)

food_security <- tuesdata$food_security

# Option 2: Read directly from GitHub

food_security <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-10-14/food_security.csv')


```

```{r factors}
food_security$Item <- as.factor(food_security$Item)
food_security$Area <- as.factor(food_security$Area)
View(food_security)
str(food_security)

```



## Selecting only ??? Data

```{r selecting for countries in South America}

food_south <- food_security %>%
  filter(Area == c("Argentina", "Bolivia", "Brazil", "Chile","Colombia", "Ecuador",
                   "Guyana", "Paraguay", "Uruguay", "Peru", "Suriname", "Venezuela (Bolivarian Republic of)")  
         )
View(food_south)

```

```{r Children Graph}
children_food <- food_south %>% 
  filter(Item %in% c(
    "Number of children under 5 years of age who are overweight (modeled estimates) (million)", 
    "Number of children under 5 years of age who are stunted (modeled estimates) (million)")) %>% 
  select(Year_Start, Year_End, Area, Item, Value)

children_food %>% 
  ggplot(aes(x = fct_reorder(Area, Value), y = Value, fill = Item)) +
  geom_col(position = "dodge") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.direction = "vertical",
        legend.position = "bottom") +
  scale_fill_manual(name = "Child Condition",
    values = c(
      "Number of children under 5 years of age who are overweight (modeled estimates) (million)" = "blue",
      "Number of children under 5 years of age who are stunted (modeled estimates) (million)" = "limegreen"),
    labels = c(
      "Number of children under 5 years of age who are overweight (modeled estimates) (million)" = "Overweight",
      "Number of children under 5 years of age who are stunted (modeled estimates) (million)" = "Stunted")) +
  labs(x = NULL,
       title = "Number of Children Modeled to be Overweight or Stunted",
       y = "Number of Children (millions)")
#add facet_wrap to plot overweight vs stunted in separate graphs
```

